/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DetailItem: typeof import('./src/components/DetailItem.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    FlagIcon: typeof import('./src/components/FlagIcon.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MetricItem: typeof import('./src/components/MetricItem.vue')['default']
    OsLogo: typeof import('./src/components/OsLogo.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    Progress: typeof import('./src/components/ui/progress/Progress.vue')['default']
    RegionFilter: typeof import('./src/components/RegionFilter.vue')['default']
    SegmentedProgress: typeof import('./src/components/SegmentedProgress.vue')['default']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    ServerCard: typeof import('./src/components/ServerCard.vue')['default']
    ServerDetailDialog: typeof import('./src/components/ServerDetailDialog.vue')['default']
    ServerTable: typeof import('./src/components/ServerTable.vue')['default']
    SettingItem: typeof import('./src/components/SettingItem.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    StatsOverview: typeof import('./src/components/StatsOverview.vue')['default']
    StatusChart: typeof import('./src/components/StatusChart.vue')['default']
    StatusIndicator: typeof import('./src/components/StatusIndicator.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    ToggleGroup: typeof import('./src/components/ui/toggle-group/ToggleGroup.vue')['default']
    ToggleGroupItem: typeof import('./src/components/ui/toggle-group/ToggleGroupItem.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    UptimeText: typeof import('./src/components/UptimeText.vue')['default']
  }
}
